Traceback (most recent call last):
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Draw all bits
tpls = [(mol,x,biAll) for x in fpAll.GetOnBits()]
Draw.DrawMorganBits(tpls[:100],molsPerRow=4,legends=[str(x) for x in fpAll.GetOnBits()][:100])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m [38;5;66;03m#Draw all bits[39;00m
[0;32m----> 2[0m tpls [38;5;241m=[39m [(mol,x,biAll) [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m [43mfpAll[49m[38;5;241m.[39mGetOnBits()]
[1;32m      3[0m Draw[38;5;241m.[39mDrawMorganBits(tpls[:[38;5;241m100[39m],molsPerRow[38;5;241m=[39m[38;5;241m4[39m,legends[38;5;241m=[39m[[38;5;28mstr[39m(x) [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m fpAll[38;5;241m.[39mGetOnBits()][:[38;5;241m100[39m])

[0;31mNameError[0m: name 'fpAll' is not defined

